name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["feature", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a [user type], I want to [do something], so that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks work)
        - High (important but has workaround)
        - Medium (nice to have)
        - Low (future enhancement)
    validations:
      required: true

  - type: checkboxes
    id: security-impact
    attributes:
      label: Security Considerations
      description: Does this feature have security implications?
      options:
        - label: This feature handles sensitive data
        - label: This feature modifies update logic
        - label: This feature adds new dependencies
        - label: No security impact

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references
      placeholder: Add links, screenshots, or related issues

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false
