name: Security Vulnerability
description: Report a security vulnerability (PRIVATE)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please report it privately through GitHub's security advisory feature instead of opening a public issue.

        [Report a Security Vulnerability](../../security/advisories/new)

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: What is the security issue?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How severe is this vulnerability?
      options:
        - Critical (remote code execution, credential theft)
        - High (privilege escalation, authentication bypass)
        - Medium (denial of service, information disclosure)
        - Low (minor security concern)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact?
      placeholder: |
        - Who is affected?
        - What data/systems are at risk?
        - What can an attacker do?
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: |
        - v0.1.0
        - v0.2.0 - v0.5.0
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps (if applicable)
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Step 1
        2. Step 2
      value: |
        <!-- REMOVE sensitive details before submitting publicly -->
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this?
      placeholder: How could this be fixed or mitigated?
    validations:
      required: false

  - type: textarea
    id: cve
    attributes:
      label: CVE or Reference
      description: Any CVE numbers or external references?
      placeholder: CVE-2024-XXXXX, link to advisory, etc.
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      options:
        - label: I will allow 90 days for a fix before public disclosure
          required: false
        - label: I am willing to coordinate on the disclosure timeline
          required: false
