# Default values for safe-auto-updater

replicaCount: 1

image:
  repository: safe-auto-updater
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  enableDocker: false
  enableKubernetes: true
  
  kubernetes:
    namespace: default
    labels:
      auto-update: "enabled"
  
  semver:
    allowMajorUpdates: false
    allowMinorUpdates: true
    allowPatchUpdates: true
  
  healthCheck:
    timeout: 60
    interval: 5
    retries: 3
  
  update:
    autoUpdate: true
    autoRollback: true
    waitForHealth: true
    createBackup: true

logging:
  level: INFO
