# Production-Grade Safe Auto-Updater Policy
# This configuration demonstrates a production setup with strict safety controls

auto_update:
  update_policy:
    enabled: true
    max_concurrent: 2  # Conservative: only 2 concurrent updates
    update_window: "03:00-05:00"  # Narrow maintenance window
    dry_run: false

  semver_gates:
    patch: auto        # Trust patch updates
    minor: review      # Review minor updates for breaking changes
    major: manual      # Always require manual approval for major versions
    prerelease: skip   # Never auto-update pre-releases in production

  health_checks:
    # Multi-layer health validation
    - type: http
      http:
        endpoint: /health/ready
        timeout: 45
        retries: 5
        expected_status: 200
        method: GET
        headers:
          X-Health-Check: "safe-updater"

    - type: http
      http:
        endpoint: /health/live
        timeout: 30
        retries: 3
        expected_status: 200

    - type: kubernetes
      # Rely on Kubernetes probes as final validation

  rollback:
    auto_rollback: true
    failure_threshold: 0.05  # Very strict: rollback at 5% failure
    monitoring_duration: 600  # Monitor for 10 minutes
    max_rollback_attempts: 5

docker:
  socket_path: /var/run/docker.sock
  watchtower_enabled: true
  watchtower_endpoint: http://watchtower:8080

kubernetes:
  kubeconfig_path: /home/updater/.kube/config
  namespace: production
  in_cluster: true
  service_account: safe-updater-sa

monitoring:
  prometheus_enabled: true
  prometheus_port: 9090
  metrics_path: /metrics
  log_level: INFO
